# TCL File Generated by Component Editor 9.1
# Mon Aug 23 04:14:29 UYT 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | z80avalonmm "z80avalonmm" v2.0
# | Leonardo Etcheverry 2010.08.23.04:14:29
# | Memory-mapped Z80 to Avalon MM Master Bridge
# | 
# | /mnt/shared/clean/bridged_jtaguart/z80avalonmm.vhd
# | 
# |    ./z80avalonmm.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module z80avalonmm
# | 
set_module_property DESCRIPTION "Memory-mapped Z80 to Avalon MM Master Bridge"
set_module_property NAME z80avalonmm
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property GROUP "Bridges and Adapters/Memory Mapped"
set_module_property AUTHOR "Leonardo Etcheverry"
set_module_property DISPLAY_NAME z80avalonmm
set_module_property TOP_LEVEL_HDL_FILE z80avalonmm.vhd
set_module_property TOP_LEVEL_HDL_MODULE Z80AvalonMM
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file z80avalonmm.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_master
# | 
add_interface avalon_master avalon start
set_interface_property avalon_master associatedClock clock_reset
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master linewrapBursts false

set_interface_property avalon_master ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_master ENABLED true

add_interface_port avalon_master waitrequest_n waitrequest_n Input 1
add_interface_port avalon_master address address Output 32
add_interface_port avalon_master write_n write_n Output 1
add_interface_port avalon_master read_n read_n Output 1
add_interface_port avalon_master writedata writedata Output 32
add_interface_port avalon_master readdata readdata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end ADDR export Input 8
add_interface_port conduit_end CS_n export Input 1
add_interface_port conduit_end RD_n export Input 1
add_interface_port conduit_end WR_n export Input 1
add_interface_port conduit_end IORQ_n export Input 1
add_interface_port conduit_end DAT_O export Output 8
add_interface_port conduit_end INT_n export Output 1
add_interface_port conduit_end DAT_I export Input 8
add_interface_port conduit_end WAIT_n export Output 1
# | 
# +-----------------------------------
